// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscoverPeersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverPeersRequest) Reset()         { *m = DiscoverPeersRequest{} }
func (m *DiscoverPeersRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoverPeersRequest) ProtoMessage()    {}
func (*DiscoverPeersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *DiscoverPeersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverPeersRequest.Unmarshal(m, b)
}
func (m *DiscoverPeersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverPeersRequest.Marshal(b, m, deterministic)
}
func (m *DiscoverPeersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverPeersRequest.Merge(m, src)
}
func (m *DiscoverPeersRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoverPeersRequest.Size(m)
}
func (m *DiscoverPeersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverPeersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverPeersRequest proto.InternalMessageInfo

type DiscoverPeersResponse struct {
	Peers                []*Peer  `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverPeersResponse) Reset()         { *m = DiscoverPeersResponse{} }
func (m *DiscoverPeersResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverPeersResponse) ProtoMessage()    {}
func (*DiscoverPeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1}
}

func (m *DiscoverPeersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverPeersResponse.Unmarshal(m, b)
}
func (m *DiscoverPeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverPeersResponse.Marshal(b, m, deterministic)
}
func (m *DiscoverPeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverPeersResponse.Merge(m, src)
}
func (m *DiscoverPeersResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverPeersResponse.Size(m)
}
func (m *DiscoverPeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverPeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverPeersResponse proto.InternalMessageInfo

func (m *DiscoverPeersResponse) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*DiscoverPeersRequest)(nil), "api.DiscoverPeersRequest")
	proto.RegisterType((*DiscoverPeersResponse)(nil), "api.DiscoverPeersResponse")
}

func init() {
	proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0)
}

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8,
	0x94, 0xe2, 0x49, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x08, 0x29, 0x89, 0x71, 0x89, 0xb8, 0x40,
	0x55, 0x05, 0xa4, 0xa6, 0x16, 0x15, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x59, 0x70,
	0x89, 0xa2, 0x89, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xc9, 0x73, 0xb1, 0x16, 0x80, 0x04,
	0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x38, 0xf5, 0x12, 0x0b, 0x32, 0xf5, 0x40, 0x4a, 0x82,
	0x20, 0xe2, 0x46, 0xc1, 0x5c, 0x9c, 0x30, 0x9d, 0x95, 0x42, 0x6e, 0x5c, 0xbc, 0x28, 0xc6, 0x08,
	0x49, 0x82, 0xd5, 0x63, 0xb3, 0x52, 0x4a, 0x0a, 0x9b, 0x14, 0xc4, 0x56, 0x27, 0xf6, 0x28, 0x56,
	0x3d, 0xfd, 0xc4, 0x82, 0xcc, 0x24, 0x36, 0xb0, 0xb3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd0, 0x64, 0x6b, 0x2f, 0xdc, 0x00, 0x00, 0x00,
}
