// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.0--rc1
// source: executor.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareLocalEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project        *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ContainerImage string   `protobuf:"bytes,2,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
}

func (x *PrepareLocalEnvRequest) Reset() {
	*x = PrepareLocalEnvRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareLocalEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareLocalEnvRequest) ProtoMessage() {}

func (x *PrepareLocalEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareLocalEnvRequest.ProtoReflect.Descriptor instead.
func (*PrepareLocalEnvRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareLocalEnvRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *PrepareLocalEnvRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

type PrepareLocalEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PrepareLocalEnvResponse) Reset() {
	*x = PrepareLocalEnvResponse{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareLocalEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareLocalEnvResponse) ProtoMessage() {}

func (x *PrepareLocalEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareLocalEnvResponse.ProtoReflect.Descriptor instead.
func (*PrepareLocalEnvResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareLocalEnvResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubmitAndExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`          // cmd 所属项目信息
	CmdId   string   `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"` // cmd id
}

func (x *SubmitAndExecuteRequest) Reset() {
	*x = SubmitAndExecuteRequest{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndExecuteRequest) ProtoMessage() {}

func (x *SubmitAndExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndExecuteRequest.ProtoReflect.Descriptor instead.
func (*SubmitAndExecuteRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitAndExecuteRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *SubmitAndExecuteRequest) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

type SubmitAndExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`               // 返回成功信号
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                       // 任务id
	Executor *Peer  `protobuf:"bytes,3,opt,name=executor,proto3" json:"executor,omitempty"`           // 任务是在哪个executor执行完成的
	NFail    int32  `protobuf:"varint,4,opt,name=nFail,proto3" json:"nFail,omitempty"`                // 失败了几次 NFS可能导致文件系统忙，有时候需要重试
	StdOut   string `protobuf:"bytes,5,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"` // 命令执行标准输出
	StdErr   string `protobuf:"bytes,6,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"` // 命令执行标准错误
}

func (x *SubmitAndExecuteResponse) Reset() {
	*x = SubmitAndExecuteResponse{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAndExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAndExecuteResponse) ProtoMessage() {}

func (x *SubmitAndExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAndExecuteResponse.ProtoReflect.Descriptor instead.
func (*SubmitAndExecuteResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitAndExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitAndExecuteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitAndExecuteResponse) GetExecutor() *Peer {
	if x != nil {
		return x.Executor
	}
	return nil
}

func (x *SubmitAndExecuteResponse) GetNFail() int32 {
	if x != nil {
		return x.NFail
	}
	return 0
}

func (x *SubmitAndExecuteResponse) GetStdOut() string {
	if x != nil {
		return x.StdOut
	}
	return ""
}

func (x *SubmitAndExecuteResponse) GetStdErr() string {
	if x != nil {
		return x.StdErr
	}
	return ""
}

type CleanupLocalEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
}

func (x *CleanupLocalEnvRequest) Reset() {
	*x = CleanupLocalEnvRequest{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupLocalEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupLocalEnvRequest) ProtoMessage() {}

func (x *CleanupLocalEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupLocalEnvRequest.ProtoReflect.Descriptor instead.
func (*CleanupLocalEnvRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *CleanupLocalEnvRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type CleanupLocalEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CleanupLocalEnvResponse) Reset() {
	*x = CleanupLocalEnvResponse{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupLocalEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupLocalEnvResponse) ProtoMessage() {}

func (x *CleanupLocalEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupLocalEnvResponse.ProtoReflect.Descriptor instead.
func (*CleanupLocalEnvResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *CleanupLocalEnvResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_executor_proto protoreflect.FileDescriptor

var file_executor_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x16, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x31,
	0x0a, 0x17, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e,
	0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x58, 0x0a, 0x17, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x64, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6d, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x18,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x25, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x08, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x46, 0x61, 0x69, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x74, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x64, 0x5f, 0x65, 0x72,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x64, 0x45, 0x72, 0x72, 0x22,
	0x40, 0x0a, 0x16, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45,
	0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x31, 0x0a, 0x17, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0x81, 0x02, 0x0a, 0x12, 0x53, 0x68, 0x61, 0x72, 0x65, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x4c, 0x0a, 0x0f, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x12, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e,
	0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x10, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x41, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x64, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0f, 0x43, 0x6c,
	0x65, 0x61, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x12, 0x1b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData = file_executor_proto_rawDesc
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(file_executor_proto_rawDescData)
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_executor_proto_goTypes = []any{
	(*PrepareLocalEnvRequest)(nil),   // 0: api.PrepareLocalEnvRequest
	(*PrepareLocalEnvResponse)(nil),  // 1: api.PrepareLocalEnvResponse
	(*SubmitAndExecuteRequest)(nil),  // 2: api.SubmitAndExecuteRequest
	(*SubmitAndExecuteResponse)(nil), // 3: api.SubmitAndExecuteResponse
	(*CleanupLocalEnvRequest)(nil),   // 4: api.CleanupLocalEnvRequest
	(*CleanupLocalEnvResponse)(nil),  // 5: api.CleanupLocalEnvResponse
	(*Project)(nil),                  // 6: api.Project
	(*Peer)(nil),                     // 7: api.Peer
}
var file_executor_proto_depIdxs = []int32{
	6, // 0: api.PrepareLocalEnvRequest.project:type_name -> api.Project
	6, // 1: api.SubmitAndExecuteRequest.project:type_name -> api.Project
	7, // 2: api.SubmitAndExecuteResponse.executor:type_name -> api.Peer
	6, // 3: api.CleanupLocalEnvRequest.project:type_name -> api.Project
	0, // 4: api.ShareBuildExecutor.PrepareLocalEnv:input_type -> api.PrepareLocalEnvRequest
	2, // 5: api.ShareBuildExecutor.SubmitAndExecute:input_type -> api.SubmitAndExecuteRequest
	4, // 6: api.ShareBuildExecutor.CleanupLocalEnv:input_type -> api.CleanupLocalEnvRequest
	1, // 7: api.ShareBuildExecutor.PrepareLocalEnv:output_type -> api.PrepareLocalEnvResponse
	3, // 8: api.ShareBuildExecutor.SubmitAndExecute:output_type -> api.SubmitAndExecuteResponse
	5, // 9: api.ShareBuildExecutor.CleanupLocalEnv:output_type -> api.CleanupLocalEnvResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_executor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_rawDesc = nil
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
