// Code generated by protoc-gen-go. DO NOT EDIT.
// source: executor.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrepareLocalEnvRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ContainerImage       string   `protobuf:"bytes,2,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareLocalEnvRequest) Reset()         { *m = PrepareLocalEnvRequest{} }
func (m *PrepareLocalEnvRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareLocalEnvRequest) ProtoMessage()    {}
func (*PrepareLocalEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{0}
}

func (m *PrepareLocalEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareLocalEnvRequest.Unmarshal(m, b)
}
func (m *PrepareLocalEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareLocalEnvRequest.Marshal(b, m, deterministic)
}
func (m *PrepareLocalEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareLocalEnvRequest.Merge(m, src)
}
func (m *PrepareLocalEnvRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareLocalEnvRequest.Size(m)
}
func (m *PrepareLocalEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareLocalEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareLocalEnvRequest proto.InternalMessageInfo

func (m *PrepareLocalEnvRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *PrepareLocalEnvRequest) GetContainerImage() string {
	if m != nil {
		return m.ContainerImage
	}
	return ""
}

type PrepareLocalEnvResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareLocalEnvResponse) Reset()         { *m = PrepareLocalEnvResponse{} }
func (m *PrepareLocalEnvResponse) String() string { return proto.CompactTextString(m) }
func (*PrepareLocalEnvResponse) ProtoMessage()    {}
func (*PrepareLocalEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{1}
}

func (m *PrepareLocalEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareLocalEnvResponse.Unmarshal(m, b)
}
func (m *PrepareLocalEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareLocalEnvResponse.Marshal(b, m, deterministic)
}
func (m *PrepareLocalEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareLocalEnvResponse.Merge(m, src)
}
func (m *PrepareLocalEnvResponse) XXX_Size() int {
	return xxx_messageInfo_PrepareLocalEnvResponse.Size(m)
}
func (m *PrepareLocalEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareLocalEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareLocalEnvResponse proto.InternalMessageInfo

func (m *PrepareLocalEnvResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SubmitAndExecuteRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	CmdId                string   `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitAndExecuteRequest) Reset()         { *m = SubmitAndExecuteRequest{} }
func (m *SubmitAndExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitAndExecuteRequest) ProtoMessage()    {}
func (*SubmitAndExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{2}
}

func (m *SubmitAndExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitAndExecuteRequest.Unmarshal(m, b)
}
func (m *SubmitAndExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitAndExecuteRequest.Marshal(b, m, deterministic)
}
func (m *SubmitAndExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAndExecuteRequest.Merge(m, src)
}
func (m *SubmitAndExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitAndExecuteRequest.Size(m)
}
func (m *SubmitAndExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAndExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAndExecuteRequest proto.InternalMessageInfo

func (m *SubmitAndExecuteRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *SubmitAndExecuteRequest) GetCmdId() string {
	if m != nil {
		return m.CmdId
	}
	return ""
}

type SubmitAndExecuteResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	StdOut               string   `protobuf:"bytes,3,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	StdErr               string   `protobuf:"bytes,4,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitAndExecuteResponse) Reset()         { *m = SubmitAndExecuteResponse{} }
func (m *SubmitAndExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitAndExecuteResponse) ProtoMessage()    {}
func (*SubmitAndExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{3}
}

func (m *SubmitAndExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitAndExecuteResponse.Unmarshal(m, b)
}
func (m *SubmitAndExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitAndExecuteResponse.Marshal(b, m, deterministic)
}
func (m *SubmitAndExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitAndExecuteResponse.Merge(m, src)
}
func (m *SubmitAndExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitAndExecuteResponse.Size(m)
}
func (m *SubmitAndExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitAndExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitAndExecuteResponse proto.InternalMessageInfo

func (m *SubmitAndExecuteResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SubmitAndExecuteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SubmitAndExecuteResponse) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *SubmitAndExecuteResponse) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

type CleanupLocalEnvRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanupLocalEnvRequest) Reset()         { *m = CleanupLocalEnvRequest{} }
func (m *CleanupLocalEnvRequest) String() string { return proto.CompactTextString(m) }
func (*CleanupLocalEnvRequest) ProtoMessage()    {}
func (*CleanupLocalEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{4}
}

func (m *CleanupLocalEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanupLocalEnvRequest.Unmarshal(m, b)
}
func (m *CleanupLocalEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanupLocalEnvRequest.Marshal(b, m, deterministic)
}
func (m *CleanupLocalEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanupLocalEnvRequest.Merge(m, src)
}
func (m *CleanupLocalEnvRequest) XXX_Size() int {
	return xxx_messageInfo_CleanupLocalEnvRequest.Size(m)
}
func (m *CleanupLocalEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanupLocalEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CleanupLocalEnvRequest proto.InternalMessageInfo

func (m *CleanupLocalEnvRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type CleanupLocalEnvResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanupLocalEnvResponse) Reset()         { *m = CleanupLocalEnvResponse{} }
func (m *CleanupLocalEnvResponse) String() string { return proto.CompactTextString(m) }
func (*CleanupLocalEnvResponse) ProtoMessage()    {}
func (*CleanupLocalEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12d1cdcda51e000f, []int{5}
}

func (m *CleanupLocalEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanupLocalEnvResponse.Unmarshal(m, b)
}
func (m *CleanupLocalEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanupLocalEnvResponse.Marshal(b, m, deterministic)
}
func (m *CleanupLocalEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanupLocalEnvResponse.Merge(m, src)
}
func (m *CleanupLocalEnvResponse) XXX_Size() int {
	return xxx_messageInfo_CleanupLocalEnvResponse.Size(m)
}
func (m *CleanupLocalEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanupLocalEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CleanupLocalEnvResponse proto.InternalMessageInfo

func (m *CleanupLocalEnvResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*PrepareLocalEnvRequest)(nil), "api.PrepareLocalEnvRequest")
	proto.RegisterType((*PrepareLocalEnvResponse)(nil), "api.PrepareLocalEnvResponse")
	proto.RegisterType((*SubmitAndExecuteRequest)(nil), "api.SubmitAndExecuteRequest")
	proto.RegisterType((*SubmitAndExecuteResponse)(nil), "api.SubmitAndExecuteResponse")
	proto.RegisterType((*CleanupLocalEnvRequest)(nil), "api.CleanupLocalEnvRequest")
	proto.RegisterType((*CleanupLocalEnvResponse)(nil), "api.CleanupLocalEnvResponse")
}

func init() {
	proto.RegisterFile("executor.proto", fileDescriptor_12d1cdcda51e000f)
}

var fileDescriptor_12d1cdcda51e000f = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x4b, 0x02, 0x41,
	0x18, 0x65, 0xd7, 0x5c, 0xf1, 0x53, 0x34, 0x06, 0x72, 0x17, 0x2b, 0x90, 0x0d, 0xca, 0xd3, 0x46,
	0x76, 0x8f, 0x32, 0x3c, 0x08, 0x82, 0xb2, 0x5e, 0xa2, 0x8b, 0x8c, 0x3b, 0x1f, 0x35, 0xe1, 0xee,
	0x4c, 0xb3, 0x33, 0xd1, 0xd5, 0xff, 0x3c, 0x5a, 0x47, 0x21, 0x7f, 0x1c, 0xec, 0xfa, 0x1e, 0xfb,
	0x7e, 0x7c, 0x6f, 0x07, 0x1a, 0xf8, 0x8d, 0x89, 0xd1, 0x42, 0x45, 0x52, 0x09, 0x2d, 0x48, 0x89,
	0x4a, 0xde, 0xae, 0x27, 0x22, 0x4d, 0x45, 0xb6, 0x82, 0x42, 0x0e, 0xad, 0x89, 0x42, 0x49, 0x15,
	0x8e, 0x44, 0x42, 0x17, 0x83, 0xec, 0x2b, 0xc6, 0x4f, 0x83, 0xb9, 0x26, 0xd7, 0x50, 0x91, 0x4a,
	0x7c, 0x60, 0xa2, 0x03, 0xa7, 0xe3, 0x74, 0x6b, 0xbd, 0x7a, 0x44, 0x25, 0x8f, 0x26, 0x2b, 0x2c,
	0x5e, 0x93, 0xe4, 0x06, 0x9a, 0x89, 0xc8, 0x34, 0xe5, 0x19, 0xaa, 0x19, 0x4f, 0xe9, 0x1b, 0x06,
	0x6e, 0xc7, 0xe9, 0x56, 0xe3, 0xc6, 0x06, 0x1e, 0xfe, 0xa2, 0xe1, 0x03, 0xf8, 0x3b, 0x56, 0xb9,
	0x14, 0x59, 0x8e, 0xe4, 0x0a, 0xbc, 0x5c, 0x53, 0x6d, 0x72, 0x6b, 0x55, 0x2b, 0xac, 0xa6, 0x05,
	0x14, 0x5b, 0x2a, 0x7c, 0x01, 0x7f, 0x6a, 0xe6, 0x29, 0xd7, 0x4f, 0x19, 0x1b, 0x14, 0xc5, 0xf0,
	0xd8, 0xac, 0x67, 0xe0, 0x25, 0x29, 0x9b, 0x71, 0x66, 0x23, 0x96, 0x93, 0x94, 0x0d, 0x59, 0xb8,
	0x74, 0x20, 0xd8, 0x95, 0x3e, 0x22, 0x1b, 0x69, 0x80, 0xbb, 0x11, 0x75, 0x39, 0x23, 0x3e, 0x54,
	0x72, 0xcd, 0x66, 0xc2, 0xe8, 0xa0, 0x54, 0x80, 0x5e, 0xae, 0xd9, 0xd8, 0xe8, 0x35, 0x81, 0x4a,
	0x05, 0x27, 0x1b, 0x62, 0xa0, 0x54, 0xf8, 0x08, 0xad, 0xe7, 0x05, 0xd2, 0xcc, 0xc8, 0x7f, 0x0e,
	0x11, 0xde, 0x81, 0xbf, 0xa3, 0x60, 0x3b, 0xb4, 0xfe, 0x74, 0xa8, 0xae, 0x63, 0xf7, 0x96, 0x2e,
	0x90, 0xe9, 0x3b, 0x55, 0xd8, 0x37, 0x7c, 0x61, 0x9b, 0x0b, 0x45, 0x46, 0xd0, 0xdc, 0x5a, 0x8a,
	0x9c, 0x5b, 0xcf, 0x7d, 0xbf, 0x4a, 0xfb, 0x62, 0x3f, 0x69, 0xcd, 0xc7, 0x70, 0xba, 0x7d, 0x5c,
	0xb2, 0xfa, 0xe2, 0xc0, 0x9c, 0xed, 0xcb, 0x03, 0xac, 0x15, 0x1c, 0x41, 0x73, 0xab, 0xa8, 0x8d,
	0xb7, 0xff, 0x80, 0x36, 0xde, 0x81, 0xdb, 0xf4, 0x2b, 0xaf, 0xe5, 0xe8, 0x96, 0x4a, 0x3e, 0xf7,
	0x8a, 0x17, 0x71, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xce, 0x5a, 0x9f, 0x9d, 0x36, 0x03, 0x00,
	0x00,
}
