// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitializeBuildEnvRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ContainerImage       string   `protobuf:"bytes,2,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeBuildEnvRequest) Reset()         { *m = InitializeBuildEnvRequest{} }
func (m *InitializeBuildEnvRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeBuildEnvRequest) ProtoMessage()    {}
func (*InitializeBuildEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *InitializeBuildEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeBuildEnvRequest.Unmarshal(m, b)
}
func (m *InitializeBuildEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeBuildEnvRequest.Marshal(b, m, deterministic)
}
func (m *InitializeBuildEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeBuildEnvRequest.Merge(m, src)
}
func (m *InitializeBuildEnvRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeBuildEnvRequest.Size(m)
}
func (m *InitializeBuildEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeBuildEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeBuildEnvRequest proto.InternalMessageInfo

func (m *InitializeBuildEnvRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *InitializeBuildEnvRequest) GetContainerImage() string {
	if m != nil {
		return m.ContainerImage
	}
	return ""
}

type InitializeBuildEnvResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Peers                []*Peer  `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeBuildEnvResponse) Reset()         { *m = InitializeBuildEnvResponse{} }
func (m *InitializeBuildEnvResponse) String() string { return proto.CompactTextString(m) }
func (*InitializeBuildEnvResponse) ProtoMessage()    {}
func (*InitializeBuildEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *InitializeBuildEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeBuildEnvResponse.Unmarshal(m, b)
}
func (m *InitializeBuildEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeBuildEnvResponse.Marshal(b, m, deterministic)
}
func (m *InitializeBuildEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeBuildEnvResponse.Merge(m, src)
}
func (m *InitializeBuildEnvResponse) XXX_Size() int {
	return xxx_messageInfo_InitializeBuildEnvResponse.Size(m)
}
func (m *InitializeBuildEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeBuildEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeBuildEnvResponse proto.InternalMessageInfo

func (m *InitializeBuildEnvResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InitializeBuildEnvResponse) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type ForwardAndExecuteRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	CmdId                string   `protobuf:"bytes,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	CmdContent           string   `protobuf:"bytes,3,opt,name=cmd_content,json=cmdContent,proto3" json:"cmd_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardAndExecuteRequest) Reset()         { *m = ForwardAndExecuteRequest{} }
func (m *ForwardAndExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardAndExecuteRequest) ProtoMessage()    {}
func (*ForwardAndExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *ForwardAndExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardAndExecuteRequest.Unmarshal(m, b)
}
func (m *ForwardAndExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardAndExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ForwardAndExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardAndExecuteRequest.Merge(m, src)
}
func (m *ForwardAndExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardAndExecuteRequest.Size(m)
}
func (m *ForwardAndExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardAndExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardAndExecuteRequest proto.InternalMessageInfo

func (m *ForwardAndExecuteRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ForwardAndExecuteRequest) GetCmdId() string {
	if m != nil {
		return m.CmdId
	}
	return ""
}

func (m *ForwardAndExecuteRequest) GetCmdContent() string {
	if m != nil {
		return m.CmdContent
	}
	return ""
}

type ForwardAndExecuteResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Executor             *Peer    `protobuf:"bytes,3,opt,name=executor,proto3" json:"executor,omitempty"`
	StdOut               string   `protobuf:"bytes,4,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	StdErr               string   `protobuf:"bytes,5,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardAndExecuteResponse) Reset()         { *m = ForwardAndExecuteResponse{} }
func (m *ForwardAndExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardAndExecuteResponse) ProtoMessage()    {}
func (*ForwardAndExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *ForwardAndExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardAndExecuteResponse.Unmarshal(m, b)
}
func (m *ForwardAndExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardAndExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ForwardAndExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardAndExecuteResponse.Merge(m, src)
}
func (m *ForwardAndExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardAndExecuteResponse.Size(m)
}
func (m *ForwardAndExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardAndExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardAndExecuteResponse proto.InternalMessageInfo

func (m *ForwardAndExecuteResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ForwardAndExecuteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ForwardAndExecuteResponse) GetExecutor() *Peer {
	if m != nil {
		return m.Executor
	}
	return nil
}

func (m *ForwardAndExecuteResponse) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *ForwardAndExecuteResponse) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

type ClearBuildEnvRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearBuildEnvRequest) Reset()         { *m = ClearBuildEnvRequest{} }
func (m *ClearBuildEnvRequest) String() string { return proto.CompactTextString(m) }
func (*ClearBuildEnvRequest) ProtoMessage()    {}
func (*ClearBuildEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *ClearBuildEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearBuildEnvRequest.Unmarshal(m, b)
}
func (m *ClearBuildEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearBuildEnvRequest.Marshal(b, m, deterministic)
}
func (m *ClearBuildEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearBuildEnvRequest.Merge(m, src)
}
func (m *ClearBuildEnvRequest) XXX_Size() int {
	return xxx_messageInfo_ClearBuildEnvRequest.Size(m)
}
func (m *ClearBuildEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearBuildEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearBuildEnvRequest proto.InternalMessageInfo

func (m *ClearBuildEnvRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ClearBuildEnvResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearBuildEnvResponse) Reset()         { *m = ClearBuildEnvResponse{} }
func (m *ClearBuildEnvResponse) String() string { return proto.CompactTextString(m) }
func (*ClearBuildEnvResponse) ProtoMessage()    {}
func (*ClearBuildEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *ClearBuildEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearBuildEnvResponse.Unmarshal(m, b)
}
func (m *ClearBuildEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearBuildEnvResponse.Marshal(b, m, deterministic)
}
func (m *ClearBuildEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearBuildEnvResponse.Merge(m, src)
}
func (m *ClearBuildEnvResponse) XXX_Size() int {
	return xxx_messageInfo_ClearBuildEnvResponse.Size(m)
}
func (m *ClearBuildEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearBuildEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearBuildEnvResponse proto.InternalMessageInfo

func (m *ClearBuildEnvResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*InitializeBuildEnvRequest)(nil), "api.InitializeBuildEnvRequest")
	proto.RegisterType((*InitializeBuildEnvResponse)(nil), "api.InitializeBuildEnvResponse")
	proto.RegisterType((*ForwardAndExecuteRequest)(nil), "api.ForwardAndExecuteRequest")
	proto.RegisterType((*ForwardAndExecuteResponse)(nil), "api.ForwardAndExecuteResponse")
	proto.RegisterType((*ClearBuildEnvRequest)(nil), "api.ClearBuildEnvRequest")
	proto.RegisterType((*ClearBuildEnvResponse)(nil), "api.ClearBuildEnvResponse")
}

func init() {
	proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf)
}

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x1c, 0xc5, 0x95, 0x94, 0xa4, 0xec, 0x9f, 0xb1, 0x09, 0x8b, 0x89, 0x34, 0x12, 0x6b, 0x15, 0x04,
	0xf4, 0x14, 0xa4, 0x72, 0x45, 0x48, 0x6c, 0xea, 0xa4, 0x9e, 0x98, 0x32, 0x71, 0xe1, 0x52, 0x79,
	0xf1, 0x5f, 0x60, 0x94, 0xd8, 0xc6, 0x76, 0x60, 0xec, 0xcc, 0x97, 0xe1, 0x5b, 0xa2, 0x38, 0x59,
	0xa4, 0xd1, 0xe4, 0xd0, 0x5d, 0xdf, 0x4f, 0xcf, 0xcf, 0x2f, 0x7e, 0x81, 0x48, 0x69, 0x79, 0xf3,
	0x3b, 0x53, 0x5a, 0x5a, 0x49, 0x26, 0x54, 0xf1, 0xe4, 0xb0, 0x90, 0x55, 0x25, 0x45, 0x2b, 0xa5,
	0x25, 0xcc, 0x36, 0x82, 0x5b, 0x4e, 0x4b, 0x7e, 0x8b, 0x67, 0x35, 0x2f, 0xd9, 0x5a, 0xfc, 0xcc,
	0xf1, 0x47, 0x8d, 0xc6, 0x92, 0xd7, 0x30, 0x55, 0x5a, 0x7e, 0xc7, 0xc2, 0xc6, 0xde, 0xc2, 0x5b,
	0x46, 0xab, 0xc3, 0x8c, 0x2a, 0x9e, 0x5d, 0xb6, 0x5a, 0x7e, 0x07, 0xc9, 0x1b, 0x38, 0x2e, 0xa4,
	0xb0, 0x94, 0x0b, 0xd4, 0x5b, 0x5e, 0xd1, 0xaf, 0x18, 0xfb, 0x0b, 0x6f, 0x79, 0x90, 0x1f, 0xf5,
	0xf2, 0xa6, 0x51, 0xd3, 0x6b, 0x48, 0x86, 0xd2, 0x8c, 0x92, 0xc2, 0x20, 0x79, 0x09, 0xa1, 0xb1,
	0xd4, 0xd6, 0xa6, 0x4b, 0x8b, 0x5c, 0xda, 0x95, 0x93, 0xf2, 0x0e, 0x91, 0x39, 0x04, 0x0a, 0x51,
	0x9b, 0xd8, 0x5f, 0x4c, 0x96, 0xd1, 0xea, 0xa0, 0xbd, 0x11, 0xa2, 0xce, 0x5b, 0x3d, 0xbd, 0x85,
	0xf8, 0x42, 0xea, 0x5f, 0x54, 0xb3, 0x8f, 0x82, 0xad, 0x6f, 0xb0, 0xa8, 0x2d, 0xee, 0x5b, 0xe8,
	0x04, 0xc2, 0xa2, 0x62, 0x5b, 0xce, 0xba, 0x1e, 0x41, 0x51, 0xb1, 0x0d, 0x23, 0x73, 0x88, 0x1a,
	0xb9, 0x29, 0x85, 0xc2, 0xc6, 0x13, 0xc7, 0xa0, 0xa8, 0xd8, 0x79, 0xab, 0xa4, 0x7f, 0x3d, 0x98,
	0x0d, 0x84, 0xef, 0xd3, 0xef, 0x08, 0xfc, 0x3e, 0xd6, 0xe7, 0x8c, 0xbc, 0x82, 0xc7, 0xe8, 0xce,
	0x91, 0xda, 0x05, 0xde, 0xab, 0xdc, 0x23, 0xf2, 0x1c, 0xa6, 0xc6, 0xb2, 0xad, 0xac, 0x6d, 0xfc,
	0xc8, 0x79, 0x43, 0x63, 0xd9, 0xa7, 0xda, 0xde, 0x01, 0xd4, 0x3a, 0x0e, 0x7a, 0xb0, 0xd6, 0x3a,
	0xfd, 0x00, 0xcf, 0xce, 0x4b, 0xa4, 0xfa, 0x81, 0x8f, 0x9e, 0xbe, 0x87, 0x93, 0xff, 0xfc, 0x7b,
	0xd4, 0x5c, 0xfd, 0xf1, 0xe1, 0xf8, 0xea, 0x1b, 0xd5, 0xed, 0x0a, 0x2e, 0x9b, 0x91, 0x92, 0xcf,
	0x40, 0x76, 0xd7, 0x41, 0x4e, 0x9d, 0x7d, 0x74, 0xa4, 0xc9, 0x7c, 0x94, 0x77, 0xf7, 0xc9, 0xe1,
	0xe9, 0xce, 0x9b, 0x90, 0x17, 0xce, 0x35, 0x36, 0x94, 0xe4, 0x74, 0x0c, 0x77, 0x67, 0x5e, 0xc0,
	0x93, 0x7b, 0xe5, 0xc9, 0xcc, 0x19, 0x86, 0x3e, 0x68, 0x92, 0x0c, 0xa1, 0xf6, 0x9c, 0xb3, 0xe9,
	0x97, 0x20, 0x7b, 0x4b, 0x15, 0xbf, 0x0e, 0xdd, 0xef, 0xf8, 0xee, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0x13, 0xab, 0xa3, 0xb0, 0x03, 0x00, 0x00,
}
